import { Prisma, ExecutionTime } from "@/lib/generated/prisma/client";

export const MOCK_TASKS: Prisma.TaskCreateInput[] = [
    {
        title: "Składanie szafy PAX (3 moduły) z lustrem",
        description:
            "Szukam sprawnego fachowca do złożenia szafy PAX z IKEA. Trzy moduły, w tym jedne drzwi lustrzane. Wszystkie paczki są już w mieszkaniu na 2. piętrze (jest winda). Narzędzia własne wymagane.",
        categorySlug: "montaz-i-naprawy",
        location: "Warszawa, Mokotów",
        price: 350,
        isBoosted: true,
        executionTime: ExecutionTime.WITHIN_FEW_DAYS,
        authorName: "Mariusz W.",
        authorAvatar:
            "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 4.9,
        authorRatingCount: 24,
    },
    {
        title: "Dokładne sprzątanie mieszkania 55m² po remoncie",
        description:
            "Potrzebuję pomocy w doprowadzeniu mieszkania do porządku po malowaniu. Do umycia są 4 okna, kurze w szafkach kuchennych oraz dokładne odkurzenie i zmycie pyłu budowlanego.",
        categorySlug: "sprzatanie",
        location: "Warszawa, Ursynów",
        price: 280,
        isBoosted: false,
        executionTime: ExecutionTime.THIS_WEEKEND,
        authorName: "Anna Kowalska",
        authorAvatar:
            "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 5.0,
        authorRatingCount: 12,
    },
    {
        title: "Przewóz kanapy narożnej i wniesienie na 3. piętro",
        description:
            "Zlecenie polega na odebraniu kanapy ze sklepu meblowego na Targówku i przewiezieniu jej na Wolę. Wymagane wniesienie na 3. piętro (brak windy). Potrzebne 2 osoby.",
        categorySlug: "transport",
        location: "Warszawa, Wola",
        price: 200,
        isBoosted: true,
        executionTime: ExecutionTime.ASAP,
        authorName: "Piotr S.",
        authorAvatar: null,
        authorVerified: false,
        authorRating: 4.5,
        authorRatingCount: 5,
    },
    {
        title: "Wyprowadzanie Labradora (3 razy dziennie, weekend)",
        description:
            "Szukam odpowiedzialnej osoby do opieki nad rocznym labradorem w nadchodzący weekend. Pies jest łagodny i usłuchany. Spacery po ok. 45 minut w okolicach Parku Szczęśliwickiego.",
        categorySlug: "zwierzeta",
        location: "Warszawa, Ochota",
        price: 150,
        isBoosted: false,
        executionTime: ExecutionTime.THIS_WEEKEND,
        authorName: "Magda M.",
        authorAvatar:
            "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 4.8,
        authorRatingCount: 18,
    },
    {
        title: "Skoszenie trawnika 400m² i przycięcie żywopłotu",
        description:
            "Zlecę uporządkowanie ogródka. Do skoszenia jest około 400m² trawy oraz równe przycięcie żywopłotu z tui. Posiadam kosiarkę spalinową i nożyce elektryczne.",
        categorySlug: "ogrod",
        location: "Warszawa, Wilanów",
        price: 250,
        isBoosted: false,
        executionTime: ExecutionTime.FLEXIBLE,
        authorName: "Janusz G.",
        authorAvatar: null,
        authorVerified: true,
        authorRating: 4.2,
        authorRatingCount: 3,
    },
    {
        title: "Zrobienie i dostarczenie ciężkich zakupów (Castorama)",
        description:
            "Potrzebuję kogoś, kto pojedzie do Castoramy, zakupi 4 worki ziemi ogrodowej oraz korę i dostarczy mi je pod drzwi. Prześlę dokładną listę produktów.",
        categorySlug: "zakupy",
        location: "Warszawa, Wawer",
        price: 90,
        isBoosted: true,
        executionTime: ExecutionTime.ASAP,
        authorName: "Helena Rucińska",
        authorAvatar: null,
        authorVerified: false,
        authorRating: 4.7,
        authorRatingCount: 9,
    },
    {
        title: "Naprawa cieknącej spłuczki podtynkowej Geberit",
        description:
            "Woda cały czas delikatnie sączy się do muszli klozetowej. Prawdopodobnie uszczelka zaworu spustowego jest do wymiany. Szukam kogoś z doświadczeniem.",
        categorySlug: "montaz-i-naprawy",
        location: "Warszawa, Śródmieście",
        price: 180,
        isBoosted: false,
        executionTime: ExecutionTime.WITHIN_FEW_DAYS,
        authorName: "Krzysztof Ł.",
        authorAvatar:
            "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 4.6,
        authorRatingCount: 15,
    },
    {
        title: "Mycie witryn sklepowych (lokal użytkowy, parter)",
        description:
            "Zlecę umycie dużych przeszklonych witryn w salonie fryzjerskim. Łącznie 4 duże szyby od ziemi do wysokości 2.5m, mycie z dwóch stron. Rano przed 8:00.",
        categorySlug: "sprzatanie",
        location: "Warszawa, Bemowo",
        price: 120,
        isBoosted: false,
        executionTime: ExecutionTime.FLEXIBLE,
        authorName: "Karolina Nowak",
        authorAvatar: null,
        authorVerified: true,
        authorRating: 4.9,
        authorRatingCount: 42,
    },
    {
        title: "Przeprowadzka kawalerki – przewóz kartonów i AGD",
        description:
            "Szukam osoby z autem dostawczym (typu bus). Do przewiezienia około 15 kartonów, mikrofalówka, mała lodówka oraz materac. Pomagam przy załadunku.",
        categorySlug: "transport",
        location: "Warszawa, Praga-Południe",
        price: 220,
        isBoosted: false,
        executionTime: ExecutionTime.WITHIN_FEW_DAYS,
        authorName: "Tomasz B.",
        authorAvatar:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
        authorVerified: false,
        authorRating: 4.4,
        authorRatingCount: 7,
    },
    {
        title: "Wniesienie starej kanapy do kontenera gabarytowego",
        description:
            "Potrzebuję pomocy przy zniesieniu starej kanapy dwuosobowej z 4. piętra (brak windy) do kontenera pod blokiem. Praca na 15 minut.",
        categorySlug: "inne",
        location: "Warszawa, Żoliborz",
        price: 70,
        isBoosted: false,
        executionTime: ExecutionTime.ASAP,
        authorName: "Wojciech S.",
        authorAvatar: null,
        authorVerified: true,
        authorRating: 4.1,
        authorRatingCount: 2,
    },
    {
        title: "Podłączenie płyty indukcyjnej i piekarnika (uprawnienia SEP)",
        description:
            "Potrzebuję elektryka z uprawnieniami SEP do podłączenia nowej płyty indukcyjnej oraz piekarnika w nowym budownictwie. Wymagany wpis do karty gwarancyjnej.",
        categorySlug: "montaz-i-naprawy",
        location: "Warszawa, Białołęka",
        price: 200,
        isBoosted: true,
        executionTime: ExecutionTime.ASAP,
        authorName: "Michał K.",
        authorAvatar:
            "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 4.9,
        authorRatingCount: 31,
    },
    {
        title: "Pranie tapicerki meblowej (narożnik + 2 fotele)",
        description:
            "Zlecę ekstrakcyjne czyszczenie jasnego narożnika oraz dwóch foteli. Meble wymagają odświeżenia po dzieciach i psie. Proszę o wykonanie usługi u mnie w domu.",
        categorySlug: "sprzatanie",
        location: "Warszawa, Mokotów",
        price: 230,
        isBoosted: false,
        executionTime: ExecutionTime.THIS_WEEKEND,
        authorName: "Katarzyna P.",
        authorAvatar: null,
        authorVerified: true,
        authorRating: 4.7,
        authorRatingCount: 8,
    },
    {
        title: "Korepetycje z matematyki przed maturą (poziom podstawowy)",
        description:
            "Szukam cierpliwego korepetytora dla licealisty z klasy maturalnej. Chodzi o powtórzenie funkcji i ciągów oraz rozwiązywanie arkuszy. Spotkania 2 razy w tygodniu.",
        categorySlug: "inne",
        location: "Warszawa, Targówek",
        price: 90,
        isBoosted: false,
        executionTime: ExecutionTime.FLEXIBLE,
        authorName: "Ewa Z.",
        authorAvatar:
            "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 5.0,
        authorRatingCount: 19,
    },
    {
        title: "Montaż 3 rolet zewnętrznych/wewnętrznych w kasecie",
        description:
            "Do zamontowania są 3 rolety w kasecie z prowadnicami na okna plastikowe w sypialni i salonie. Rolety są docięte na wymiar, do wywiercenia otwory.",
        categorySlug: "montaz-i-naprawy",
        location: "Warszawa, Ochota",
        price: 160,
        isBoosted: false,
        executionTime: ExecutionTime.WITHIN_FEW_DAYS,
        authorName: "Robert D.",
        authorAvatar: null,
        authorVerified: false,
        authorRating: 4.3,
        authorRatingCount: 4,
    },
    {
        title: "Opieka nad kotem (karmienie i kuweta, 1x dziennie)",
        description:
            "Szukam zaufanej osoby, która w dniach 1-5 sierpnia wpadnie raz dziennie do mojego mieszkania, nasypie karmy, wymieni wodę i sprzątnie kuwetę u spokojnego kota.",
        categorySlug: "zwierzeta",
        location: "Warszawa, Śródmieście",
        price: 180,
        isBoosted: false,
        executionTime: ExecutionTime.FLEXIBLE,
        authorName: "Patrycja W.",
        authorAvatar:
            "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 4.9,
        authorRatingCount: 16,
    },
    {
        title: "Przewóz 4 opon samochodowych do wulkanizacji",
        description:
            "Potrzebuję zabrać 4 opony z piwnicy (R17), przewieźć do zakładu wulkanizacyjnego oddalonego o 3 km i po wymianie przywieźć stare opony z powrotem.",
        categorySlug: "transport",
        location: "Warszawa, Ursynów",
        price: 100,
        isBoosted: false,
        executionTime: ExecutionTime.WITHIN_FEW_DAYS,
        authorName: "Łukasz M.",
        authorAvatar: null,
        authorVerified: true,
        authorRating: 4.0,
        authorRatingCount: 1,
    },
    {
        title: "Malowanie małej łazienki (ok. 6m²) farbą hydrofobową",
        description:
            "Do odświeżenia sufit oraz górna część ścian w łazience po usunięciu starych zacieków. Farba dedykowana do łazienek kupiona na miejscu. Praca na parę godzin.",
        categorySlug: "montaz-i-naprawy",
        location: "Warszawa, Wola",
        price: 300,
        isBoosted: true,
        executionTime: ExecutionTime.THIS_WEEKEND,
        authorName: "Grzegorz N.",
        authorAvatar:
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 4.8,
        authorRatingCount: 22,
    },
    {
        title: "Nasadzenie 20 tui wzdłuż ogrodzenia",
        description:
            "Potrzebuję pomocy fizycznej przy wykopaniu dołków, wsypaniu odpowiedniej ziemi i posadzeniu 20 sadzonek tui szmaragd (wysokość ok. 100cm). Ziemia na miejscu.",
        categorySlug: "ogrod",
        location: "Warszawa, Wawer",
        price: 200,
        isBoosted: false,
        executionTime: ExecutionTime.FLEXIBLE,
        authorName: "Stanisław T.",
        authorAvatar: null,
        authorVerified: false,
        authorRating: 0,
        authorRatingCount: 0,
    },
    {
        title: "Zakupy spożywcze dla osoby starszej (z wniesieniem)",
        description:
            "Zlecę zrobienie cotygodniowych zakupów w Biedronce/Lidlu dla mojej babci wg przygotowanej listy i wniesienie ich na 2. piętro. Płatność za zakupy przelewem Blik.",
        categorySlug: "zakupy",
        location: "Warszawa, Praga-Północ",
        price: 70,
        isBoosted: false,
        executionTime: ExecutionTime.ASAP,
        authorName: "Dominika C.",
        authorAvatar:
            "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150",
        authorVerified: true,
        authorRating: 5.0,
        authorRatingCount: 10,
    },
    {
        title: "Umycie okien w domu jednorodzinnym (8 okien)",
        description:
            "Zlecę dokładne umycie 8 okien dwuskrzydłowych oraz jednych drzwi tarasowych w domu parterowym. Dostęp z ziemi/drabinki. Środki i sprzęt dostarczam.",
        categorySlug: "sprzatanie",
        location: "Warszawa, Wilanów",
        price: 250,
        isBoosted: true,
        executionTime: ExecutionTime.WITHIN_FEW_DAYS,
        authorName: "Monika K.",
        authorAvatar: null,
        authorVerified: true,
        authorRating: 4.6,
        authorRatingCount: 14,
    },
];
